### PR TITLE
Add CSS variables for cell height

### PR DESCRIPTION
**Pull request by davitykale-zz**
Necessary for Shadow DOM

---
This change is [Reviewable](https://reviewable.io/reviews/saulis/iron-data-table/165)

### CODE REVIEW

**Comment by Saulis** [comment]
Hi and thanks! Would it be more useful if we add mixins for the cells instead? What do you think?

**Comment by davitykale-zz** [comment]
Sure! Either sounds good to me :)

**Comment by Saulis** [comment]
Hi!

Sorry for the delay! Now that I actually looked more into this matter, what's actually the use case this? As you can currently just normally style:

``` css
iron-data-table data-table-cell {
  height: 100px;
}
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/165#-:-KWrT8aE0KSp2ZQrbrIp:b-w00u23)_

**Comment by Storyyeller** [comment]
That doesn't work with the shadow dom.

**Comment by Storyyeller** [comment]
But https://github.com/Saulis/iron-data-table/pull/147 is more general, so I think you should go with that instead.

**Comment by Storyyeller** [comment]
In retrospect, I think this is useful independently of #147, since height has to be applied to both the checkbox and the cell, and we probably don't want the same mixin to apply to cell and checkbox.

Of course, that would require this to be modified to add the variables to checkbox as well.

**Pull request closed without merging**
