### PR TITLE
SortOrder not handled as Array: issue #29

### LINKED ISSUE #29: SortOrder not handled as Array
In iron-data-table sortOrder can be an array to allow multiple sort columns but in data-table-column-sort is handled as plain object. Also sort arrows are not accessible, why just not use paper-icon-button?

Here is a patch allowing configure the sort position in the sortOrder and change div by paper-icon-button to make #sortIcon accessible (only need to configure aria-label, need change iron-data-table also); also allow clear state up-down-newClick sequence -> direction must be reset and propagated to the UI:

``` diff
Index: x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/iron-data-table/data-table-column-sort.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/iron-data-table/data-table-column-sort.html   (revision )
+++ x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/iron-data-table/data-table-column-sort.html   (revision )
@@ -10,38 +10,43 @@
         margin: 4px;
       }

-      #sortIcon {
+      paper-icon-button {
-        position: relative;
+          position: relative;
-        width: 24px;
-        height: 24px;
+          opacity: .16;
       }

-      iron-icon {
-        fill: rgba(0, 0, 0, .16);
-        cursor: pointer;
-        padding: 0px;
+      paper-icon-button[active], paper-icon-button:hover, paper-icon-button[focused] {
+          opacity: .84;
+      }
+
+      paper-icon-button ::content iron-icon {
+        padding: 0;
         --iron-icon-width: 24px;
         --iron-icon-height: 24px;
         transition: all .2s;
       }

-      iron-icon[active], iron-icon:hover {
-        fill: rgba(0, 0, 0, .87);
+      paper-icon-button[direction='desc'][active] ::content iron-icon {
+        transform: rotate(-180deg);
       }

-      paper-ripple {
-        color: rgba(0, 0, 0, .54);
+      paper-icon-button[direction]:after {
+        content: attr(sort-order);
+        font-size: 9px;
+        font-weight: bold;
+        position: absolute;
+        right: 4px;
+        bottom: 8px;
       }
-
-      #sortIcon[direction='desc'] iron-icon[active] {
-        transform: rotate(-180deg);
-      }
     </style>

-    <div id="sortIcon" on-tap="_sort" hidden="[[hidden]]" direction$="[[direction]]">
-      <iron-icon active$="[[_isActive(path, sortOrder)]]" icon="arrow-upward"></iron-icon>
-      <paper-ripple class="circle" center></paper-ripple>
-    </div>
+    <paper-icon-button id="sortIcon"
+                       on-tap="_sort"
+                       hidden="[[hidden]]"
+                       icon="arrow-upward"
+                       active="[[_isActive(path, sortOrder)]]"
+                       direction$="[[direction]]"
+                       sort-order$="[[_computeSortOrder(path, sortOrder)]]"></paper-icon-button>

   </template>
   <script>
@@ -49,7 +54,10 @@
       is: 'data-table-column-sort',

       properties: {
-        direction: String,
+        direction: {
+            type: String,
+            notify: true
+        },
         hidden: Boolean,
         path: String,
         sortOrder: {
@@ -59,13 +67,45 @@
       },

       _isActive: function(path, sortOrder) {
+        if(Array.isArray(sortOrder)) {
+          return sortOrder.find(function(item) {
+            return item.path == path;
+          }) !== undefined;
+        }
         return path === sortOrder.path;
       },

       _sortOrderChanged: function(sortOrder) {
+        if(Array.isArray(sortOrder)) {
+          var path = this.path;
+          var sort = sortOrder.find(function(item) {
+            return item.path == path;
+          });
+          if(sort) {
+            this.direction = sort.direction;
+          } else {
+            this.direction = null;
+          }
+        } else {
-        if (sortOrder.path === this.path) {
-          this.direction = sortOrder.direction;
+          if (sortOrder.path === this.path) {
+            this.direction = sortOrder.direction;
+          } else {
+            this.direction = null;
-        }
+          }
+        }
+      },
+
+      _computeSortOrder: function(path, sortOrder) {
+        if(Array.isArray(sortOrder)) {
+          var sort = sortOrder.find(function(item) {
+            return item.path == path;
+          });
+          return sort && sort.order ? sort.order: null;
+        }
+        if (path === sortOrder.path) {
+          return sortOrder.order ? sortOrder.order : null;
+        }
+        return null;
       },

       _sort: function() {
```

### PR DESCRIPTION
**Pull request by userquin**
Fixes #29 

This change is [Reviewable](https://reviewable.io/reviews/saulis/iron-data-table/30)

### CODE REVIEW

**Comment by Saulis** [comment]
Could you make separate pull requests for any additional fix you've done for the selection changed event and flexible layout so I can review them separately? Thanks!

**Comment by userquin** [comment]
I have uploaded a new pull request for selection change event but my
computer crash (SSD is dead), I need to install operating system so I
cannot send you flex layout but it is simple:

Go to https://github.com/userquin/iron-data-table/tree/master/demo, master
branch and get this files:

fill.html
fill-component.html
fill-header.html
fill-header-component.html

and modify your index.html and all demo pages to include links to fill.html
and fill-header.html (you can see in my repo under demo/index-html)

2016-03-28 9:10 GMT+02:00 Sauli Tähkäpää notifications@github.com:

**Comment by userquin** [comment]
also get fill-theme.html

2016-03-28 20:36 GMT+02:00 Joaquín Sánchez userquin@gmail.com:

**Comment by Saulis** [comment]
Closed in #34

**Pull request closed without merging**
