### PR TITLE
Row Details

### LINKED ISSUE #49: Selected template property has invalid value when Select All has been checked.

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #49

This change is [Reviewable](https://reviewable.io/reviews/saulis/iron-data-table/52)

### CODE REVIEW

**Comment by gazal-k** [comment]
Tests pass, let me know if I should add more

---

Reviewed 1 of 6 files at r1, 5 of 9 files at r2, 3 of 5 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/52#-:-KGB9ujTzmNDN_Z0wXkr:917107906)_

**Comment by gazal-k** [comment]
Oh wait, actually, there's just 1 thing, the reflectToAttribute on expanded does not have any effect anymore since notify is false. might as well get rid of it

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/52#-:-KGBBwLDKFLJnA63a-z_:-114265786)_

**Comment by Saulis** [comment]
But it does, it still reflects the property value as an attribute. `notify: false` just prevents it from firing `expanded-changed` events automatically.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/52#-:-KGBPgfd-ykiNXnKs1nd:-781550976)_

**Comment by gazal-k** [comment]
You're right. My tests actually did verify the attribute. My bad

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/52#-:-KGBex_6rjhvy_56_HyL:1513649450)_

**Comment by raffaeu** [comment]
Guys, any ETA on when this feature will be available? I am going to replace vaadin-grid with yours but I need the details working and able to load an extra `iron-data-table` inside the details of a row

**Comment by Saulis** [comment]
Hi!

I'd planned adding Angular 2 support for the row details - but actually I could merge this as it is to master and then do the ng2 fix separately. Can you manage with using the master branch until I'm able to crank out a new release (in about a week or so) ?

**Comment by raffaeu** [comment]
Sure I can do a git locally from your master.

Thanks

**Comment by gazal-k** [comment]
@raffaeu you could even work of this feature branch till @Saulis releases this.
Your bower dependency would be: 

``` json
"iron-data-table": "Saulis/iron-data-table#feature/row-detail"
```

**Pull request merged**
