### PR TITLE
minor fix for dart porting

### PR DESCRIPTION
**Pull request by dam0vm3nt**
I've ported your nice element to Dart (see [here](https://pub.dartlang.org/packages/custom_elements)) but I had to apply this patch to make it work.

Could you merge it ?

### CODE REVIEW

**Comment by Saulis** [comment]
Hi there, and thanks for PR!

I think I need to modify it a bit, would it be OK for you if an empty array would be set to `iron-list` when `items` is `null`

**Comment by dam0vm3nt** [comment]
I imagine this would be even better. My solution was not working well with Firefox. But I'll check it as soon as you had patched it.

**Comment by dam0vm3nt** [comment]
Should I close the PR or do you still need it?

**Comment by Saulis** [comment]
I can use this PR as a base. Could you try if branch `fix/null-items` works for you?

`bower install iron-data-table#fix/null-items` 

Thanks!

**Comment by dam0vm3nt** [comment]
lgtm

It works like a charm, tnx.

**Pull request closed without merging**
