### PR TITLE
Row Details feature

### PR DESCRIPTION
**Pull request by gazal-k**
@Saulis pls see if this approach is OK. I'm still not very clear on `Polymer.Templatizer`.
Also, no idea whether this will work properly with angularjs2.

---

This change is [Reviewable](https://reviewable.io/reviews/saulis/iron-data-table/45)

### CODE REVIEW

**Comment by Saulis** [comment]
Hi and thanks for making the effort for looking into this feature!

I probably won't have time to dig really deep into this pull request until next week, but I'll try to give some quick comments. If you want to discuss in more detail, I'd be happy to talk with you on the Gitter chat (see the link next to the Build status badge on the repository readme)

---

Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

_[data-table-column.html, line 100 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVigyA_xi6D7KHKDPz:-KFViXruh46S7RPUJC-9:217811182) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-column.html#L100)):_
Not sure if this is needed. I'd leave it out for now.

---

_[data-table-row-detail.html, line 10 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeqWJDv2tZ3jmJWnM:-KFVeqWJDv2tZ3jmJWnN:571575862) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L10)):_
The custom mixin can be left out, this element will be placed in the light DOM.

---

_[data-table-row-detail.html, line 31 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVcztPaksxHhfzlkDK:-KFVcztQNqrNK2O4kBXZ:638415856) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L31)):_
In order to make `Templatizer` work in all kinds of different path forwarding methods need to be implemented. You can have a look how `data-table-column` has been done. But, no need to worry about them at this point yet – I'll help in implementing and testing them.

---

_[data-table-row-detail.html, line 37 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVdjYtzlu5i_1uazgW:-KFVdjYuQ_SLVfbGthZC:-1527926541) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L37)):_
You should rather consider taking in the template as a property for this component. The `detail` property could be renamed to `rowDetailTemplate` to be explicit about it.

---

_[data-table-row-detail.html, line 52 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeKjsnMn2uLqayZV4:-KFVeKjsnMn2uLqayZV5:-1490433542) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L52)):_
These kinds of return objects are used in other templates to enable easier integration for Angular 2 templates. You can ignore all that at this point, we can come back to that at later point.

---

_[data-table-row.html, line 49 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVfBQX577tw5I0Vxi-:-KFVfBQX577tw5I0Vxi0:-245941072) ([raw file](https://github.com/saulis/iron-data-table/blob/153457b19675d11b56bc34d88c211646cf025858/data-table-row.html#L49)):_
`<data-table-row-detail>` should be placed inside `<data-table-row>` so this change can be reverted.

---

_[iron-data-table.html, line 165 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVilbu3M9up1ftDbg-:-KFVilbu3M9up1ftDbg0:1822788535) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L165)):_
This shouldn't be needed after the details are placed inside `data-table-row` 

---

_[iron-data-table.html, line 199 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhpsKtEfsz_j_1AcD:-KFVhpsKtEfsz_j_1AcE:-121563792) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L199)):_
How the user should expand the row details has been a question mark for me. I'm thinking there should always be a visual indicator telling the user if a row is expandable or not. And still, clicking/tapping on the row is in conflict with selecting the row.

One option would be to have a separate icon/button for expanding the details. Something like the `data-table-checkbox` element. What do you think?

---

_[iron-data-table.html, line 202 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVfUoitrkIJKIwybwg:-KFVfUoitrkIJKIwybwh:1403459822) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L202)):_
`<data-table-row-detail>` needs to be placed inside `<data-table-row>` to expose it in the light DOM of `<iron-data-table>` which is needed for custom styling purposes when using Shadow DOM. 

The tricky part here is that `<data-table-row>` is using `display: flex` currently to layout the cells nicely, so you need to wrap the cells in a container div and transfer the current layout styles from row that container.

---

_[iron-data-table.html, line 202 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVk0aH-IbV3Poi332c:-KFVk0aH-IbV3Poi332d:636758428) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L202)):_
Might be simpler just have `on-dom-change="notifyResize"`

---

_[iron-data-table.html, line 211 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhH43EqUcsHUAy_J7:-KFVhH43EqUcsHUAy_J8:-1658886482) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L211)):_
I'd prefer using `<template is="row-detail">` kind of syntax here instead of classes even if `is` attribute is not a native attribute, it's the same way as  dom-repeat etc. are done.

---

_[iron-data-table.html, line 400 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVj-B0KZ_SpxtlMbav:-KFVj-B0KZ_SpxtlMbaw:987728315) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L400)):_
I'd use attribute ´is` instead of classes here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-:-KFVcS6qoU3GBRwoDgLg:742251001)_

**Comment by gazal-k** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

_[data-table-column.html, line 100 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVigyA_xi6D7KHKDPz:-KFXTXwxuw0UQbLi-fg0:-221982684) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-column.html#L100)):_
for cases were we'd want to show row detail on clicking the row, but for some columns, for e.g. a column with a button or a drop down, we'd like to skip showing the detail and let the tap work for the content within that column

---

_[data-table-row-detail.html, line 52 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeKjsnMn2uLqayZV4:-KFXViZq66vbGQTc4LVy:1791513367) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L52)):_
Should I remove it?

---

_[iron-data-table.html, line 199 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhpsKtEfsz_j_1AcD:-KFXWARuSSPZHJasBd_l:-2000586707) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L199)):_
I initially tried to leverage the iron-list selection feature itself. The problem with that approach was that, the details section functionality would be very limited.

The details functionality as I've implemented can only work with selectionEnabled = false. I think a lot of UX designers ask for the row details to work on clicking any part of the row. Couldn't find anything here: http://www.google.com/design/spec/components/data-tables.html.

---

_[iron-data-table.html, line 202 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVk0aH-IbV3Poi332c:-KFXZpcTIh9oPaDrzocq:-1985948964) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L202)):_
I think I tried `notifyResize`, but let me check again.

---

_[iron-data-table.html, line 211 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhH43EqUcsHUAy_J7:-KFX_3Z5S4zVwUDaupkD:732723644) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L211)):_
Ah OK, now I understand your comment about taking the template as a property in `data-table-row-detail`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

_[data-table-column.html, line 100 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVigyA_xi6D7KHKDPz:-KFXzHcIq7BF0cTXInUu:-1149290580) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-column.html#L100)):_
Usually in those cases focusable elements like button and input fields capture the tap events so that they are not propagated to their parents. I think `<iron-list>` was doing that at some point but can't seem to find anything related to that now. 

So by default, `<iron-data-table>` would check that if the tap was originally targeted for an focusable element inside any cell element, it won't fire any selection/expand action for that item. Therefore, this property might become redundant.

---

_[data-table-row-detail.html, line 52 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeKjsnMn2uLqayZV4:-KFY9MdTMKYejTWr2itX:575594930) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L52)):_
We can leave it and just ignore it for now.

---

_[iron-data-table.html, line 199 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhpsKtEfsz_j_1AcD:-KFY2YOpiYoJRfluK7i4:616517789) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L199)):_
Yeah the MD specs really don't specify anything about expanding rows. List of Cards is maybe the closest match. Iron-list has also a demo with collapsing items: https://elements.polymer-project.org/elements/iron-list?view=demo:demo/collapse.html&active=iron-list, but I think they also don't select any items on click. Notice the visual `[+]` indicator on hover. 

I agree that clicking on the whole row area would be better than an icon, but the conflict with selection need to be figured out. I see a few options:

a) Selection and Row details are mutually exclusive features
b) Selection is the primary action for row, details has an icon
c) Row details is the primary action for row, selection has an icon
d) Selection is the primary action when selection is enabled, otherwise row details is 
e) ?

Currently, I feel it's a must to support both selection and row details at the same time (I might be convinced otherwise :smile:), and I feel it's really important to have a visual indicator that the row can be expanded, even if the clickable area would be larger. 

As a first step, I would like to add an down-arrow, `+` or a vertical `...` icon to indicate if a row can be expanded. After that, we could experiment having the expand row toggle area for the whole row element if selection is disabled. I guess the third step would then be to decide how to deal with the situation when both selection and row details is enabled.

For the placement of the icon, I'm not sure. Row start becomes quite crowded if there is the checkbox visible at the same time – row end can be hidden if there are many columns.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by gazal-k** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

_[data-table-column.html, line 100 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVigyA_xi6D7KHKDPz:-KFZ7W8MdxbAJ8IH5uzo:750445163) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-column.html#L100)):_
Currently, it looks like when I place a button in a cell, the event is propagating up. If we can fix that, this property will definitely become redundant/obsolete.

---

_[iron-data-table.html, line 199 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhpsKtEfsz_j_1AcD:-KFZAyXTgFWz3rsPrL9o:-903312529) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L199)):_
I'm really not sure which way we should go either. Currently I've gone with a). About the visual indicator, I don't know if we should decide on it. Some users might need a visual indicator at row start, some at row end.

What I've done now is, I've added an attribute `row-detail` to `data-table-row`.  When I use `iron-data-table`, I add a column like this

``` html
<data-table-column flex="0" width="1.5em">
  <template>
    <iron-icon class="select" icon="icons:arrow-drop-down"></iron-icon>
    <iron-icon class="deselect" icon="app-icons:arrow-right"></iron-icon>
  </template>
</data-table-column>
```

And I've custom styling like this:

``` css
data-table-row .select,  data-table-row[selected] .deselect, data-table-row[row-detail] .deselect {
  display: none;
}

data-table-row[selected] .select, data-table-row[row-detail] .select, data-table-row .deselect {
  display: block;
}
```

We could bring this css inside the element.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by gazal-k** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

_[data-table-row-detail.html, line 10 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeqWJDv2tZ3jmJWnM:-KFZGiVU7pKu836lcLes:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L10)):_
Done.

---

_[data-table-row-detail.html, line 37 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVdjYtzlu5i_1uazgW:-KFZGmUGafkW-CW6xWmo:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L37)):_
Done.

---

_[data-table-row.html, line 49 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVfBQX577tw5I0Vxi-:-KFZGpTlyEFUNdBz8f5P:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/153457b19675d11b56bc34d88c211646cf025858/data-table-row.html#L49)):_
Done.

---

_[iron-data-table.html, line 165 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVilbu3M9up1ftDbg-:-KFZGqZamJZNcsJFrhCg:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L165)):_
Done.

---

_[iron-data-table.html, line 202 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVk0aH-IbV3Poi332c:-KFZGXdUVyVE8ChuHlFq:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L202)):_
Done.

---

_[iron-data-table.html, line 202 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVfUoitrkIJKIwybwg:-KFZG_W9jIzJvXCaKYf1:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L202)):_
Done.

---

_[iron-data-table.html, line 211 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhH43EqUcsHUAy_J7:-KFZGatpyt-rE5Cr4Txa:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L211)):_
Done.

---

_[iron-data-table.html, line 400 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVj-B0KZ_SpxtlMbav:-KFZGcNuf2Prq4dSOg4w:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L400)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by Saulis** [comment]
Starting to look good, I'll try to make a patch during this week which would prevent row actions if user has clicked on a focusable element. 

---

Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

_[data-table-column.html, line 100 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVigyA_xi6D7KHKDPz:-KFbzynsLWWI9uxE0Xw8:-361633138) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-column.html#L100)):_
Yeah, I can fix that in a separate branch.

---

_[data-table-row.html, line 34 [r2]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFc0_PjCXv1cdtzDlIc:-KFc0_PjCXv1cdtzDlId:19267914) ([raw file](https://github.com/saulis/iron-data-table/blob/7cb68a7941de96ba4582875c1e796b5fdb35abec/data-table-row.html#L34)):_
Is  `<content select="template[is=dom-repeat]">...` needed?

---

_[iron-data-table.html, line 199 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhpsKtEfsz_j_1AcD:-KFcGQVlAW5Iaiaf_Vt8:-1743330400) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L199)):_
Yeah, I think you're right. It's probably better at this point to leave built-in visual indicators and all the complexity out since for the user its easy just to add a column with an arrow icon.

For the activation, I'm thinking of adding an event that is fired when a row is clicked that allows users to customize the selection/row expansion behavior.

---

_[iron-data-table.html, line 407 [r2]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFcGJPauvMh48L9m4Yg:-KFcGJPauvMh48L9m4Yh:74801507) ([raw file](https://github.com/saulis/iron-data-table/blob/7cb68a7941de96ba4582875c1e796b5fdb35abec/iron-data-table.html#L407)):_
This could've actually been left inside the mutation observer still, but no biggie :smile: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-:-KFcJIkcQNnUHDJUEnrD:-1584781802)_

**Comment by gazal-k** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

_[data-table-row.html, line 34 [r2]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFc0_PjCXv1cdtzDlIc:-KFcezA_p2NZ35nEzqo8:-1062343275) ([raw file](https://github.com/saulis/iron-data-table/blob/7cb68a7941de96ba4582875c1e796b5fdb35abec/data-table-row.html#L34)):_
I'm not sure. For changes to `columns` property in `iron-data-table` I wanted further `data-table-cell` elements to come within `div.columns`

---

_[iron-data-table.html, line 199 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhpsKtEfsz_j_1AcD:-KFcfK_KxFwPkVlrm2ug:1673865312) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L199)):_
Are you suggesting not to keep the logic for showing the row detail within `iron-data-table`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_[iron-data-table.html, line 199 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVhpsKtEfsz_j_1AcD:-KFcjxcxofuCIoRtenFn:16212861) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/iron-data-table.html#L199)):_
No, it should be kept inside the component – but it should be customizable. One way would be to fire an event on row click, which user could catch and call `e.preventDefault()` to disable the default actions, whether it would be selection or row detail expansion. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by gazal-k** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_[data-table-row-detail.html, line 10 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeqWJDv2tZ3jmJWnM:-KFh1UTOGfIVgoUMnqER:-1369115791) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L10)):_
Actually, the element is not placed in light DOM (am I right in assuming that if an element has style class `iron-data-table` then it is in local DOM and not light DOM?). Should we add the mixin back? Or can you tell me how to put this in light dom. Also I noticed that data-table-cell is also not in light dom.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_[data-table-row-detail.html, line 10 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeqWJDv2tZ3jmJWnM:-KFiV1IZqRS5cHBpl33Q:-793068405) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L10)):_
`<data-table-row>` elements are moved to the light DOM of `<iron-data-table>` during initialization and hence every child it has is also moved. The style classes might not actually reflect that correctly when using Shady DOM, but it's more obvious when you enable native Shadow DOM.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by gazal-k** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

_[data-table-row-detail.html, line 10 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeqWJDv2tZ3jmJWnM:-KFiay4H_WV-EwrD56pd:1536976723) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L10)):_
Isn't shady DOM still the default when using polymer? How do we get around this now?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by gazal-k** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[iron-data-table.html, line 407 [r2]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFcGJPauvMh48L9m4Yg:-KFn23EknrYYWPqOfDWl:-499146009) ([raw file](https://github.com/saulis/iron-data-table/blob/7cb68a7941de96ba4582875c1e796b5fdb35abec/iron-data-table.html#L407)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by Saulis** [comment]
I'll have some time on my hands tomorrow, I'll use it to add some changes and aim to get this feature merged. I would appreciate if you'd have the time to rebase this PR to origin/master before that. Thanks!

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_[data-table-column.html, line 100 [r4]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFuH6lJqKHVdf3wR4Op:-KFuH6lJqKHVdf3wR4Oq:-171849497) ([raw file](https://github.com/saulis/iron-data-table/blob/75f89d6a70303d0913a4d16142bd69cebca0d167/data-table-column.html#L100)):_
If you take a look at the latest commits in master, I've added a change which stops item from being selected if an input inside a cell is tapped. Haven't tested it yet, but it should also stop the row detail from opening.

---

_[data-table-row-detail.html, line 10 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeqWJDv2tZ3jmJWnM:-KFuGPk-Ztk2KNauF6Rg:-1446381409) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L10)):_
Take a look at the latest commits in master, I've added a call to `Polymer.StyleTransformer` in `data-table-cell` that removes the style scope from the element. Same kind of approach can be used to `data-table-row-detail`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-:-KFuHZdowCtWDSWxaiQL:-1734866768)_

**Comment by Saulis** [comment]
Added my changes to [feature/row-detail](https://github.com/Saulis/iron-data-table/compare/feature/row-detail)

Stuff still missing:
- Angular 2 support
- Proper two-way binding between properties shared with cell templates
- Proper two-way binding between parent properties

I modified the approach a bit, row now has a `expandDetails` property which is activated on tap. Couple of custom events are fired to allow customizing the tap events.

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-:-KFxzlnU69kRei4skmaf:-1898203958)_

**Comment by gazal-k** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

_[data-table-column.html, line 100 [r4]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFuH6lJqKHVdf3wR4Op:-KFydSvLQgyDVUY0DDkV:-149739245) ([raw file](https://github.com/saulis/iron-data-table/blob/75f89d6a70303d0913a4d16142bd69cebca0d167/data-table-column.html#L100)):_
I checked your row-detail branch. The problem is, what about other elements, like a `paper-button`, an icon button, drop down etc. We've only handled `input` right?

---

_[data-table-row-detail.html, line 10 [r1]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFVeqWJDv2tZ3jmJWnM:-KFybNgF1R2cu0RVMk1e:-621691789) ([raw file](https://github.com/saulis/iron-data-table/blob/67087fda497903f04bbef5460efc36e04c21d932/data-table-row-detail.html#L10)):_
Removing the style scope doesn't really solve the problem. A css in the main page can style the elements whose style scope has been removed, but the ideal behavior would be to let `data-table-row-detail` get the style scope of the parent element of `iron-data-table`. This would allow styling for `data-table-row-detail` to be specified in the parent element of `iron-data-table`.

But anyway, I noticed that children of `data-table-row-detail` are getting the style scope of parent element of  `iron-data-table`. So specifying minimal styling here seems like the easiest way out. Infact, just removing the height property seems to work fine for me.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by Saulis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[data-table-column.html, line 100 [r4]](https://reviewable.io:443/reviews/saulis/iron-data-table/45#-KFuH6lJqKHVdf3wR4Op:-KG1grc03iKuox1SI0yD:869456397) ([raw file](https://github.com/saulis/iron-data-table/blob/75f89d6a70303d0913a4d16142bd69cebca0d167/data-table-column.html#L100)):_
Yeah you're absolutely right. The latest version takes all focusable elements into consideration.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/45)_

**Comment by gazal-k** [comment]
Closing this PR since #52 has all the changes

**Pull request closed without merging**
