### PR TITLE
Rewrite templating

### LINKED ISSUE #8: Improvement: full two-way binding support for custom headers
Currently, this doesn't work:

```
<template is="dom-bind">
<paper-input value="{{filter}}"></paper-input>
 <iron-data-table>
  <data-table-column>
    <template is="header">
      <paper-input value="{{filter}}"></paper-input>
    </template>
   <template>
     [[item.data]]
   </template>
  </data-table-column>
</iron-data-table>
</template>
```

`filter` only propagates from parent to the header, but not in the other direction. Weirdly, if `filter` is also bound to row templates, it's starts working properly.

### LINKED ISSUE #56: Notify [[item]] inside Row Details templates when items mutate.

### LINKED ISSUE #74: rowDetails do not work when iron-data-table is being wrapped by parent component
I have a component that wraps `iron-data-table` and passes in the `data-table-column`s like so:

``` html
<dom-module id="custom-grid">
  <iron-data-table>
    <content select="data-table-column"></content>
  </iron-data-table>
</dom-module>
```

When i try setting row details, however, the click handler for `iron-data-table` is consistently not being able to recognize the row-detail template passed in alongside `data-table-columns` (`this.rowDetails` is always null in line 1086 of `iron-data-table.html` even when I set it myself in the `ready` callback of the wrapper component).

### LINKED ISSUE #88: First row doesn't expand when iron-data-table is inside a parent component

### LINKED ISSUE #89: Click prevention doesn't work in Shadow DOM when inside a parent component
`document.activeElement` returns the parent node instead of the focused element inside shadow root.

### LINKED ISSUE #90: Filtering broken when injecting columns from a parent node
``` html
<!doctype html>
<head>
<meta name="description" content="iron-data-table beta3">
  <meta charset="utf-8">
  <script src="../../webcomponentsjs/webcomponents-lite.min.js"></script>
  <link href="../iron-data-table.html" rel="import">
  <link href="../default-styles.html" rel="import">
</head>
<body>
  <dom-module id="x-foo">
    <template>
      <iron-data-table items="[[items]]">
        <content select="data-table-column"></content>
      </iron-data-table>
    </template>
    <script>
      document.addEventListener('WebComponentsReady', function() {
        Polymer({
          is: 'x-foo',
          properties: {
            items: {
              value: function() {
                var items = [];

                for (var i=0; i < 100; i++) {
                  items.push({'value': 'foo'+i});
                }

                return items;
              }
            }
          }
        });
      });
    </script>
  <dom-module>

  <x-foo>
    <data-table-column name="Column 1" filter-by="value">
      <template>[[item.value]]</template>
    </data-table-column>
  </x-foo>
</body>

```

### LINKED ISSUE #92: column not available for binding in row cell templates
I would like to reopen "How to do a Dynamic table #65"

```
 <iron-data-table items="[[records]]">
     <template is="dom-repeat" items="[[origin.fields]]" as="column">
        <data-table-column name="[[column.label]]">
          <template>[[_itemValue(item,column.labe)]]</template>
        </data-table-column>
     </template>
  </iron-data-table>
```

```
 _itemValue: function(item,column) {
        return item[column)
      },
```

inside `<data-table-column name="[[column.label]]">` the column.label is not accesible. The name does appear in the header, but i can not acces it to create my itemvalue

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #8 
Fixes #56 
Fixes #74 
Fixes #88 
Fixes #89 
Fixes #90 
Fixes #92

---

This change is [Reviewable](https://reviewable.io/reviews/saulis/iron-data-table/93)

### CODE REVIEW

**Comment by web-padawan** [comment]
I've got an error then using this branch:

```
[iron-data-table::_annotatedComputationEffect]: compute method `or` not defined
```

Computed function `or` is defined in a behavior used by my element which includes `iron-data-table`.
It seems that computed functions are not processed correctly.

@Saulis please take a look.

**Comment by web-padawan** [comment]
Update: computed functions bug is still reproduced, but only then `iron-data-table` is wrapped into `dom-if` template.
E. g. we have multiple `iron-ajax` requests, and we don't want to show table until them all become completed, as `items` array is collected from their results.

**Comment by Saulis** [comment]
@web-padawan thanks for the update, I've forced push a new version, please try if it works any better.

**Comment by web-padawan** [comment]
Redefining `rootDataHost` seems to be correct now, but for some reasons polymer is now walking through DOM far too much when seeking for behaviors.

Before: 

```
[iron-data-table::_annotatedComputationEffect]: compute method `or` not defined
```

Now: 

```
[bi-projects-page::_annotatedComputationEffect]: compute method `or` not defined
```

I'm not able to provide a real example due to complexity (and the page is still WIP), but the `bi-projects-page` is more than one level up from the component which includes `iron-data-table`.

**Comment by web-padawan** [comment]
Another issue is related to data bindings from outside (see button text) which are being only applied to the first row.
datatable

**Comment by Saulis** [comment]
Right, I see. I'll try to have a better look tomorrow. Would be awesome if you provide me with some isolated example code!

**Comment by web-padawan** [comment]
Thanks. I'll try to reproduce this issue tonight in a separate repo for easier debugging.

**Comment by web-padawan** [comment]
I created a sandbox, you can see it in action [here](https://sandbox-e0d4b.firebaseapp.com/demo/table/), and the code including `iron-data-table` is [here](https://github.com/web-padawan/datatable-sandbox/blob/master/src/components/pages/sandbox-demo-table-sub-page/sandbox-demo-table-sub-page.html). 
- The bug with first line button is reproduced
- behaviors bug is reproduced too (see Status column)

```
[sandbox-demo-page::_annotatedComputationEffect]: compute method `equal` not defined
```

As you can see, behavior is expected to present in `sandbox-demo-page` - which is one level top from `sandbox-demo-table-sub-page` actually implementing this behavior.

@Saulis please pay attention to that `template` element is used to detect rootDataHost. 
I'm  trying to guess if this bug can be related to my usage of `iron-lazy-pages` element, which implements templatizer behavior itself.

**Comment by Saulis** [comment]
@web-padawan huge thanks for the sandbox! I think I was able fix the issues, assigning the root datahost follows now more closely to the default implementation. Oh and the bindings `[[equal(item.isActive, 'true')]]` were missing hyphens around the `true` if you happen to wonder why the `equal` method isn't executed when binding.

Please check out the latest version of `rewrite-templatizers`

**Comment by web-padawan** [comment]
@Saulis Thanks a lot! 
I updated the sandbox and replaced the method used in bindings to ensure it is called correctly.
All works fine with `hidden` attribute binding, as well as with `dom-if` templates.

**Comment by Saulis** [comment]
Glad to hear! Thanks for your help on this issue, I'll go ahead and merge the changes.

**Comment by Saulis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[data-table-templatizer-behavior.html, line 13 [r6]](https://reviewable.io:443/reviews/saulis/iron-data-table/93#-KLB8fXUAt6-ELG5nFGm:-KLB8fXVCaw6Jhk0SKFr:-1728701059) ([raw file](https://github.com/saulis/iron-data-table/blob/66835fe68fe33e8d1ae747ab23cf7a462f44b5e6/data-table-templatizer-behavior.html#L13)):_

> ``` HTML
>       template: Object,
> 
>       //singleton
> ```

`_instances` and `_forwardedParentProps` being singletons can be problematic when there are multiple instances of `<iron-data-table>` which have templates bound to different parent properties that have the same name.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/saulis/iron-data-table/93)_

**Pull request merged**
